# Generated by Django 5.0.6 on 2024-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("cid", models.IntegerField(primary_key=True, serialize=False)),
                ("cnm", models.CharField(max_length=34)),
                ("product", models.CharField(max_length=23)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
